# -*- coding: utf-8 -*-
"""Taylor_swift_smlproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p6IgxLbviMkJ3PQsbLYTo00z66eoeYfM
"""

# ==============================================================================
#  1. DATA LOADING & INITIAL DIAGNOSTICS
# ==============================================================================
from google.colab import files
files.upload()
import pandas as pd
df_taylor=pd.read_csv('taylor_swift_spotify.csv')
df_taylor.head()

df_taylor.info()

df_taylor.isnull().sum()

df_taylor.shape

df_taylor.duplicated().sum()

#df_taylor.columns

#3.logical grouping (album families)
#df_taylor['album'].unique()
df_taylor['album'].value_counts()

#copy album colunm and naming it album_families
df_taylor['album_families']=df_taylor['album']
#df_taylor.head()

#df_taylor.isnull().sum()

eras=['THE TORTURED POETS DEPARTMENT','Midnights','evermore','folklore','Lover','reputation','1989','Red','Speak Now','Fearless','Live From Clear Channel','Taylor Swift (Deluxe Edition)']

def map_album(album_title):
  for album_t in eras:
    if album_t in album_title:
      return album_t
  return album_title

df_taylor['album_families']=df_taylor['album'].apply(map_album)

df_taylor['album_families'] = df_taylor['album'].apply(map_album)

#df_taylor['album_families'].unique()

df_taylor['album_families'].value_counts()

#df_taylor['album_families']

# ==============================================================================
#  2. CATEGORICAL ENCODING & DATA PARTITIONING (THE DUMMY PARADOX EXPERIMENT)
# ==============================================================================
album_dummies=pd.get_dummies(df_taylor['album_families'], drop_first=True, dtype=int)
#album_dummies.head()

df_taylor=pd.concat([df_taylor, album_dummies], axis=1)
#df_taylor.head()
#df_taylor.columns

#df_taylor.describe()

x_taylor=df_taylor.drop(columns=['Unnamed: 0','name','release_date', 'album','id', 'uri','popularity','album_families'],axis=1 )
y_taylor=df_taylor['popularity']
#x_taylor.head()

# 3. split df_taylor into train-test by album families
from sklearn.model_selection import GroupShuffleSplit
gss=GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42) #The group spilt rules in general prior to impliment it on df_taylor
train_idx, test_idx=next(gss.split(x_taylor, y_taylor,groups=df_taylor['album_families']))
#print(len(train_idx)) #checking to see if the spilt workded
#print(len(test_idx))
x_train=x_taylor.iloc[train_idx].copy() #go to x_taylor and bring only the cells from train_idx
y_train=y_taylor.iloc[train_idx].copy()
x_test=x_taylor.iloc[test_idx].copy()
y_test=y_taylor.iloc[test_idx].copy()
print(x_train.shape) # 408 songs and 22 independent variable
print(y_train.shape) # 408 songs and 1 dependent variable
print("train albums (Train):", df_taylor.iloc[train_idx]['album_families'].unique())
print("test albums (Test):", df_taylor.iloc[test_idx]['album_families'].unique())

#Statistics prior to Standardization
#stas_train=x_train.describe()
#df_stas_train=pd.DataFrame(stas_train)
#df_stas_train

#4. Standardization
from sklearn.preprocessing import StandardScaler

acoustic_names = ['track_number', 'danceability', 'energy', 'loudness',
                  'speechiness', 'tempo', 'duration_ms', 'acousticness',
                  'instrumentalness', 'liveness', 'valence']
scaler = StandardScaler()
x_train[acoustic_names]=scaler.fit_transform(x_train[acoustic_names])
x_test[acoustic_names]=scaler.transform(x_test[acoustic_names])

# Statistics after Standardization
#x_train.describe()

#df_taylor['Red'].describe() # to see that the dummies columns stayed it tacked and didn't go through Standardization

#df_taylor['energy'].describe()

"""Exploratory Data Analysis (EDA)"""

# ==============================================================================
#  3. EDA
# ==============================================================================
import matplotlib.pyplot as plt
import seaborn as sns

df_temp_plot = df_taylor.copy()
df_temp_plot['album_families'] = df_temp_plot['album_families'].replace({
    'THE TORTURED POETS DEPARTMENT': 'TTPD',
    'Live From Clear Channel': 'Live',
    'Taylor Swift (Deluxe Edition)': 'Deluxe'})

plt.figure(figsize=(7.5, 3.8))

sns.boxplot(x='album_families', y='popularity', data=df_temp_plot, palette='Set2')

plt.xlabel("Album Family", fontsize=9, labelpad=6)
plt.ylabel("Song Popularity (0 - 100)", fontsize=9, labelpad=6)

plt.xticks(rotation=45, ha='right', fontsize=8)
plt.yticks(fontsize=8)

plt.grid(axis='y', linestyle=':', alpha=0.6)

plt.savefig('Song Popularity Distribution by Album Family.png', dpi=300, bbox_inches='tight')
plt.show()

plt.figure(figsize=(5, 2))
sns.boxplot(x='popularity', data=df_taylor, color='lightblue', width=0.4)
plt.xlabel("Popularity Score (0 - 100)", fontsize=10)
plt.ylabel("")
plt.savefig('Popularity Box Plot')

q1_popularity=df_taylor['popularity'].quantile(0.25)
q3_popularity=df_taylor['popularity'].quantile(0.75)
iqr_popularuty= q3_popularity - q1_popularity

lower_fence_popularity=q1_popularity - 1.5 * iqr_popularuty
upper_fence_popularity=q3_popularity + 1.5 * iqr_popularuty

print(f"The lower fence of popularity is: {lower_fence_popularity}")
print(f"The upper fence of popularity is: {upper_fence_popularity}")

outliers_popularity=df_taylor[(df_taylor['popularity']<lower_fence_popularity)|(df_taylor['popularity']>upper_fence_popularity)]
df_outliers_popularity=pd.DataFrame(outliers_popularity)
df_outliers_popularity['popularity']

df_outliers_popularity.head()

plt.figure(figsize=(9, 5))
sns.histplot(df_taylor['popularity'], kde=True, color='purple', bins=20)

plt.title("Distribution of Song Popularity", fontsize=14, fontweight='bold', pad=12)
plt.xlabel("Popularity Score (0 - 100)", fontsize=11)
plt.ylabel("Frequency", fontsize=11)
plt.grid(axis='y', linestyle=':', alpha=0.6)
plt.savefig('Distribution of Song Popularity')
plt.show()

print("Skewness:", df_taylor['popularity'].skew())

# 2. Correlation Heatmap - detacting multicollineary (loudness-energr[r=0.8], energy - acoustiness[r=-0.68], acustiness - loudness[0.67])
acoustic_heatmap=x_train[acoustic_names].corr()
plt.figure(figsize=(12, 10))
sns.heatmap(acoustic_heatmap, annot=True, cmap='coolwarm',fmt='.2f', linewidths=0.5)
plt.title('Correlation Heatmap')
plt.savefig('Corelation Heatmap')
plt.show()

# 2. Correlation Heatmap - detecting multicollinearity
acoustic_heatmap = x_train[acoustic_names].corr()

plt.figure(figsize=(6, 4.5))

sns.heatmap(
    acoustic_heatmap,
    annot=True,
    cmap='coolwarm',
    fmt='.2f',
    linewidths=0.5,
    annot_kws={"size": 6.5}
)

plt.xticks(rotation=45, ha='right', fontsize=7.5)
plt.yticks(fontsize=7.5)

plt.title('Correlation Heatmap', fontsize=10, fontweight='bold', pad=8)
plt.tight_layout()

plt.savefig('Correlation_Heatmap_Compact.png', dpi=300, bbox_inches='tight')
plt.show()

# ==============================================================================
# DIAGNOSTIC NOTE: Train Set Outlier Inspection (Commented out for production)
# ==============================================================================
# During development, I inspected the Train set distribution to ensure no
# training-specific anomalies survived.

# Boxplot (median - 65, 25% of the songs has popularity higher than 65 the divarsity is smaller in compare to songs with popularity less than 65 )
#plt.figure(figsize=(6, 4))
#sns.boxplot(x=y_train, color='lightblue')

#plt.title('Boxplot of Popularity (Train Set Outlier Detection)')
#plt.xlabel('Popularity Score')
#plt.savefig('Popularity Score')
#plt.show()
#==============================================================================

"""



Linear Model (with dummy variables)"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error,mean_absolute_error
from sklearn.metrics import r2_score

# ==============================================================================
#  4. PRELIMINARY EXPERIMENT: LINEAR REGRESSION WITH CATEGORICAL DUMMIES
# ==============================================================================
linear_model=LinearRegression().fit(x_train, y_train)
y_predict_train_linear=linear_model.predict(x_train)
rmse_train=root_mean_squared_error(y_train,y_predict_train_linear)
y_predict_test_linear=linear_model.predict(x_test)
rmse_test=root_mean_squared_error(y_test,y_predict_test_linear)
print(f"The RMSE of the train set is: {rmse_train:.4f}")
print(f"The RMSE of the test set is: {rmse_test:.4f}")

r2_score_train=r2_score(y_train, y_predict_train_linear)
r2_score_test=r2_score(y_test, y_predict_test_linear)

print(f"The R squere of the train set {r2_score_train: .4f}")
print(f"The R squere of the test set {r2_score_test: .4f}")

#x_test.columns

cof=linear_model.coef_
cof_df=pd.DataFrame(cof, index=x_train.columns, columns=['coficients'])
cof_df

"""Redefine X (x_taylor 1) to include the accustic featers and realse year insted album families




"""

# ==============================================================================
#  5. FEATURE ENGINEERING: CHRONOLOGICAL EXTRACTION & FEATURE REDEFINITION
# ==============================================================================
df_taylor['release_date'].info()

#df_taylor['release_date'].unique()

df_taylor['release_year'] = df_taylor['release_date'].str[:4].astype(int)
#df_taylor['release_year']

x_taylor1=df_taylor.drop(columns=['Unnamed: 0','name','release_date', 'album','id', 'uri','popularity','album_families','Fearless', 'Live From Clear Channel',
       'Lover', 'Midnights', 'Red', 'Speak Now',
       'THE TORTURED POETS DEPARTMENT', 'Taylor Swift (Deluxe Edition)',
       'evermore', 'folklore', 'reputation'] ,axis=1 )
y_taylor1=df_taylor['popularity']

#x_taylor1.columns

# spilt num.2
gss1=GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx1, test_idx1=next(gss1.split(x_taylor1, y_taylor1, groups=df_taylor['album_families']))
x_train1=x_taylor1.iloc[train_idx1].copy()
y_train1=y_taylor1.iloc[train_idx1].copy()
x_test1=x_taylor1.iloc[test_idx1].copy()
y_test1=y_taylor1.iloc[test_idx1].copy()

#print(x_train1.shape)
#print(y_train1.shape)
#print(x_test1.shape)
#print(y_test1.shape)
#print("Train albums (Train):", df_taylor.iloc[train_idx1]['album_families'].unique())
#print("Test albums (Test):", df_taylor.iloc[test_idx1]['album_families'].unique())

# normalizion
scaler1=StandardScaler()
x_train1[x_train1.columns]=scaler1.fit_transform(x_train1)
x_test1[x_test1.columns]=scaler1.transform(x_test1)

# testing normalizion
#x_train1.describe()

"""Linear model with all accustic features"""

linear_model1=LinearRegression().fit(x_train1, y_train1)
y1_predict_train_linear=linear_model1.predict(x_train1)
y1_predict_test_linear=linear_model1.predict(x_test1)
rmse_train1=root_mean_squared_error(y_train1, y1_predict_train_linear)
rmse_test1=root_mean_squared_error(y_test1, y1_predict_test_linear)
print(f"The RMSE of the train set with all accustic featers is: {rmse_train1:.4f}")
print(f"The RMSE of the test set with all accustic featers is: {rmse_test1:.4f}")

r21_train=r2_score(y_train1,y1_predict_train_linear)
r21_test=r2_score(y_test1,y1_predict_test_linear)
print(f"The R squere of the train set with all accustic featers {r21_train:.4f}")
print(f"The R squere of the test set with all accustic featers {r21_test:.4f}")

""" Linear model without energy"""

x_train1_loud=x_train1.drop(columns=['energy'], axis=1)
x_test1_loud=x_test1.drop(columns=['energy'], axis=1)
linear_model2=LinearRegression().fit(x_train1_loud, y_train1)
y1_predict_train_linear_loud=linear_model2.predict(x_train1_loud)
y1_predict_test_linear_loud=linear_model2.predict(x_test1_loud)
rmse_train1_loud=root_mean_squared_error(y_train1, y1_predict_train_linear_loud)
rmse_test1_loud=root_mean_squared_error(y_test1, y1_predict_test_linear_loud)
print(f"The RMSE of the train set without energy is: {rmse_train1_loud:.4f}")
print(f"The RMSE of the test set without energy is: {rmse_test1_loud:.4f}")

r21_train_loud=r2_score(y_train1,y1_predict_train_linear_loud)
r21_test_loud=r2_score(y_test1,y1_predict_test_linear_loud)
print(f"The R squere of the train set without energy {r21_train_loud:.4f}")
print(f"The R squere of the test set without energy {r21_test_loud:.4f}")

# cof of the featers of the winning model
cof_loud=linear_model2.coef_
cof_loud_df=pd.DataFrame(cof_loud, index=x_train1_loud.columns, columns=['cofiecient'])
cof_loud_df

"""Improved model - random forest tree (without 'energy')



"""

from sklearn.ensemble import RandomForestRegressor

print(f"========= Eveluate Matrics Random Forest Tree (reales year and no energy)===========")

rmse_train_forest=[]
rmse_test_forest=[]
r2_train_forest=[]
r2_test_forest=[]

for i in range(1, 11):
  forest_model=RandomForestRegressor(n_estimators=100, max_depth=i, random_state=42)
  forest_model.fit(x_train1_loud, y_train1)
  y_predict_train_forest=forest_model.predict(x_train1_loud)
  rmse_forest_train=root_mean_squared_error(y_train1, y_predict_train_forest)
  y_predict_test_forest=forest_model.predict(x_test1_loud)
  rmse_forest_test=root_mean_squared_error(y_test1, y_predict_test_forest)
  r2_forest_train=r2_score(y_train1, y_predict_train_forest)
  r2_forest_test=r2_score(y_test1, y_predict_test_forest)
  print(f"RF Deapth {i}-> Train RMSE: {rmse_forest_train:.4f} |RMSE Test: {rmse_forest_test:.4f}|R2 Train: {r2_forest_train:.4f}|R2 Test: {r2_forest_test:.4f}")


  rmse_train_forest.append(rmse_forest_train)
  rmse_test_forest.append(rmse_forest_test)
  r2_train_forest.append(r2_forest_train)
  r2_test_forest.append(r2_forest_test)

"""Improved model with accustic features and conceptual features - forest_model1"""

print(f"========== Random Forest Tree evaluation matrics (realese year with energy)==========")
rmse_train_forest1=[]
rmse_test_forest1=[]
r2_train_forest1=[]
r2_test_forest1=[]

for i in range(1, 11):
  forest_model1=RandomForestRegressor(n_estimators=100, max_depth=i, random_state=42)
  forest_model1.fit(x_train1, y_train1)
  y_predict_train_forest1=forest_model1.predict(x_train1)
  rmse_forest_train1=root_mean_squared_error(y_train1, y_predict_train_forest1)
  y_predict_test_forest1=forest_model1.predict(x_test1)
  rmse_forest_test1=root_mean_squared_error(y_test1, y_predict_test_forest1)
  r2_forest_train1=r2_score(y_train1, y_predict_train_forest1)
  r2_forest_test1=r2_score(y_test1, y_predict_test_forest1)
  rmse_train_forest1.append(rmse_forest_train1)
  rmse_test_forest1.append(rmse_forest_test1)
  r2_train_forest1.append(r2_forest_train1)
  r2_test_forest1.append(r2_forest_test1)
  print(f"RF deapth {i}-> RMSE Train: {rmse_forest_train1:.4f}| RMSE Test: {rmse_forest_test1:.4f}| R2 Train: {r2_forest_train1:.4f}| R2 Test:{r2_forest_test1:.4f}")

features_summary1 = pd.DataFrame({
    'Feature_Name': x_train1.columns,
    'Importance_Score': forest_model1.feature_importances_
})
sort_summary1=features_summary1.sort_values(by='Importance_Score',ascending=False)
print(f"======RF Importance Score with release year ===========")
sort_summary1

"""Random forest tree without release year - forest_model_pure"""

acoustic_features = ['track_number','danceability', 'loudness', 'speechiness',
                     'tempo', 'duration_ms', 'acousticness', 'instrumentalness',
                     'liveness', 'valence', 'energy']

x_pure = df_taylor[acoustic_features]
y_pure = df_taylor['popularity']

gss_pure = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx_pure, test_idx_pure = next(gss_pure.split(x_pure, y_pure, groups=df_taylor['album_families']))

x_train_pure=x_pure.iloc[train_idx_pure].copy()
y_train_pure=y_pure.iloc[train_idx_pure].copy()
x_test_pure=x_pure.iloc[test_idx_pure].copy()
y_test_pure=y_pure.iloc[test_idx_pure].copy()

scaler_pure = StandardScaler()
x_train_pure[acoustic_features] = scaler_pure.fit_transform(x_train_pure[acoustic_features])
x_test_pure[acoustic_features] = scaler_pure.transform(x_test_pure[acoustic_features])

rmse_train_pure_forest = []
rmse_test_pure_forest = []
r2_train_pure_forest = []
r2_test_pure_forest = []
for i in range(1, 11):
    forest_model_pure=RandomForestRegressor(n_estimators=100, max_depth=i, random_state=42)
    forest_model_pure.fit(x_train_pure, y_train_pure)
    y_pred_train_pure=forest_model_pure.predict(x_train_pure)
    y_pred_test_pure=forest_model_pure.predict(x_test_pure)

    rmse_tr=root_mean_squared_error(y_train_pure, y_pred_train_pure)
    rmse_te=root_mean_squared_error(y_test_pure, y_pred_test_pure)

    r2_tr=r2_score(y_train_pure, y_pred_train_pure)
    r2_te=r2_score(y_test_pure, y_pred_test_pure)
    print(f"RF deapth {i}-> RMSE Train: {rmse_tr:.4f}| RMSE Test:{rmse_te:.4f}| R2 Train: {r2_tr:.4f}| R2 Test: {r2_te:.4f}")


    rmse_train_pure_forest.append(rmse_tr)
    rmse_test_pure_forest.append(rmse_te)
    r2_train_pure_forest.append(r2_tr)
    r2_test_pure_forest.append(r2_te)

features_summary = pd.DataFrame({
    'Feature_Name': x_train_pure.columns,
    'Importance_Score': forest_model_pure.feature_importances_
})
sort_summary=features_summary.sort_values(by='Importance_Score',ascending=False)
print(f"======RF Importance Score without release year ===========")
sort_summary

"""Random Forest with max deapth none"""

forest_model5=RandomForestRegressor(n_estimators=100, max_depth=None, random_state=42)
forest_model5.fit(x_train1_loud, y_train1)
y_predict_train_forest5=forest_model5.predict(x_train1_loud)
rmse_forest_train5=root_mean_squared_error(y_train1, y_predict_train_forest5)
y_predict_test_forest5=forest_model5.predict(x_test1_loud)
rmse_forest_test5=root_mean_squared_error(y_test1, y_predict_test_forest5)
r2_forest_train5=r2_score(y_train1, y_predict_train_forest5)
r2_forest_test5=r2_score(y_test1, y_predict_test_forest5)
print(f"RF Full Deapth (none)-> RMSE Train:{rmse_forest_train5:.4f}| RMSE Test:{rmse_forest_test5:.4f}| R2 Train: {r2_forest_train5:.4f}| R2 Test{r2_forest_test5:.4f}")

# ==============================================================================
#  6. PRODUCTION SUMMARY STATISTICS (FOR TABLE 1 IN REPORT)
# ==============================================================================

df_filtered=df_taylor[df_taylor['popularity'] > 0].copy()
df_filtered['release_year'] = df_filtered['release_date'].str[:4].astype(int)
eras_list=['THE TORTURED POETS DEPARTMENT', 'Midnights', 'evermore', 'folklore',
             'Lover', 'reputation', '1989', 'Red', 'Speak Now', 'Fearless',
             'Live From Clear Channel', 'Taylor Swift (Deluxe Edition)']

df_filtered['album_families'] = df_filtered['album'].apply(lambda x: next((e for e in eras_list if e in str(x)), x))

features=['track_number', 'danceability', 'loudness', 'speechiness',
            'tempo', 'duration_ms', 'acousticness', 'instrumentalness',
            'liveness', 'valence', 'release_year']

X_clean=df_filtered[features]
y_clean=df_filtered['popularity']
groups_clean=df_filtered['album_families']

df_filtered.shape

filtered_stats=df_filtered[features+['popularity']+['energy']]
filtered_stats.describe()

numeric_cols=features+['energy']+['popularity']
for col in numeric_cols:
  skew_col=df_filtered[col].skew()
  if skew_col>0.5:
    print(f"The distribution of {col} is Right Skewed")
  elif skew_col<-0.5:
        print(f"The distribution of {col} is Left Skewed")
  else:
    print(f"The distribution of {col} is Normal")

"""Experiment: Baseline Linear Regression WITHOUT Energy (On Clean Data)"""

gss_clean=GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx_c, test_idx_c=next(gss_clean.split(X_clean, y_clean, groups=groups_clean))

X_train_c, X_test_c=X_clean.iloc[train_idx_c].copy(), X_clean.iloc[test_idx_c].copy()
y_train_c, y_test_c=y_clean.iloc[train_idx_c], y_clean.iloc[test_idx_c]

scaler_c = StandardScaler()
X_train_scaled_c=scaler_c.fit_transform(X_train_c)
X_test_scaled_c=scaler_c.transform(X_test_c)

model_clean=LinearRegression().fit(X_train_scaled_c, y_train_c)

y_pred_train_c=model_clean.predict(X_train_scaled_c)
y_pred_test_c=model_clean.predict(X_test_scaled_c)

print(f"LR Train RMSE(Without Energy): {root_mean_squared_error(y_train_c, y_pred_train_c):.4f}")
print(f"LR Test RMSE(Without Energy): {root_mean_squared_error(y_test_c, y_pred_test_c):.4f}")
print(f"LR Train R2(Without Energy): {r2_score(y_train_c, y_pred_train_c):.4f}")
print(f"LR Test R2(Without Energy): {r2_score(y_test_c, y_pred_test_c):.4f}")

""" Experiment: Baseline Linear Regression WITH Energy (On Clean Data)




"""

# ==============================================================================
# CONTROL EXPERIMENT: Linear Regression WITH Energy (On Clean Data)
# Objective: Investigate the impact of 'energy' on the linear baseline model
# after outlier removal to empirically prove multicollinearity with 'loudness'.
# ==============================================================================

# 1. Define the features list - this time INCLUDING 'energy'
features_with_energy=['track_number', 'danceability', 'energy', 'loudness', 'speechiness',
                        'tempo', 'duration_ms', 'acousticness', 'instrumentalness',
                        'liveness', 'valence', 'release_year']

# 2. Extract independent and dependent variables from the existing df_filtered
X_clean_exp=df_filtered[features_with_energy]
y_clean_exp=df_filtered['popularity']
groups_clean_exp=df_filtered['album_families']

# 3. Data Splitting using GroupShuffleSplit (Identical setup: 80/20 split, random_state=42)
gss_exp=GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx_exp, test_idx_exp = next(gss_exp.split(X_clean_exp, y_clean_exp, groups=groups_clean_exp))

X_train_exp, X_test_exp=X_clean_exp.iloc[train_idx_exp].copy(), X_clean_exp.iloc[test_idx_exp].copy()
y_train_exp, y_test_exp=y_clean_exp.iloc[train_idx_exp], y_clean_exp.iloc[test_idx_exp]

# 4. Feature Scaling (Standardization fitted strictly on the Training set)
scaler_exp=StandardScaler()
X_train_scaled_exp=scaler_exp.fit_transform(X_train_exp)
X_test_scaled_exp=scaler_exp.transform(X_test_exp)

# 5. Model Training (Linear Regression WITH energy)
model_clean_exp=LinearRegression().fit(X_train_scaled_exp, y_train_exp)

# 6. Generating predictions
y_pred_train_exp=model_clean_exp.predict(X_train_scaled_exp)
y_pred_test_exp=model_clean_exp.predict(X_test_scaled_exp)

# 7. Print the evaluation metrics for comparison

print(f"LR Train RMSE (With Energy): {root_mean_squared_error(y_train_exp, y_pred_train_exp):.4f}")
print(f"LR Test RMSE (With Energy):  {root_mean_squared_error(y_test_exp, y_pred_test_exp):.4f}")
print(f"LR Train R² (With Energy):   {r2_score(y_train_exp, y_pred_train_exp):.4f}")
print(f"LR Test R² (With Energy):    {r2_score(y_test_exp, y_pred_test_exp):.4f}")



"""Creating two CSV files for the baseline and improved models"""

# ==============================================================================
# 7. EXPORTING PRODUCTION DATASETS TO CSV
# ==============================================================================

# 1. Features for the Baseline Model (Linear Regression - Without Energy)
features_baseline = ['popularity', 'album_families', 'track_number', 'danceability', 'loudness',
                     'speechiness', 'tempo', 'duration_ms', 'acousticness', 'instrumentalness',
                     'liveness', 'valence', 'release_year']
df_taylor_baseline = df_filtered[features_baseline].copy()
df_taylor_baseline.to_csv('taylor_baseline.csv', index=False)

# 2. Features for the Improved Model (Tree-Based - With Energy)
features_improved = ['popularity', 'album_families', 'track_number', 'danceability', 'energy', 'loudness',
                     'speechiness', 'tempo', 'duration_ms', 'acousticness', 'instrumentalness',
                     'liveness', 'valence', 'release_year']
df_taylor_improved = df_filtered[features_improved].copy()
df_taylor_improved.to_csv('taylor_improved.csv', index=False)

df_live_check = df_filtered[df_filtered['album_families'].isin(['evermore', 'folklore', '1989'])]
df_live_check[df_live_check['liveness'] > 0.3][['name', 'album', 'album_families', 'liveness', 'popularity']]

df_acoustic_test = df_filtered[df_filtered['album_families'].isin(['evermore', 'folklore'])]
df_acoustic_test[df_acoustic_test['acousticness'] > 0.7][['name', 'album', 'acousticness', 'popularity']].sort_values(by='popularity')