# -*- coding: utf-8 -*-
"""winning_models_sml2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uyXYvDCp9322MANIDV5S2tEcbSqWkl57
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import root_mean_squared_error, r2_score

from google.colab import files
files.upload()
df_linear=pd.read_csv('taylor_baseline.csv')

df_linear.columns

files.upload()
df_forest=pd.read_csv('taylor_improved.csv')

df_forest.columns

"""Training a linear model"""

# 1. Linear Regression Model (Without energy and without outliers)
x_linear=df_linear.drop(columns=['popularity', 'album_families'], axis=1)
y_linear=df_linear['popularity']

# Splitting df_linear into train-test by album families
gss_linear=GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx_l, test_idx_l=next(gss_linear.split(x_linear, y_linear, groups=df_linear['album_families']))

# go to x_linear and y_linear and bring only the cells from indexes
x_train_l=x_linear.iloc[train_idx_l].copy()
y_train_l=y_linear.iloc[train_idx_l].copy()
x_test_l=x_linear.iloc[test_idx_l].copy()
y_test_l=y_linear.iloc[test_idx_l].copy()

# Feature Scaling (Normalization)
scaler_l=StandardScaler()
x_train_scaled_l=scaler_l.fit_transform(x_train_l)
x_test_scaled_l=scaler_l.transform(x_test_l)

# Training the Linear Regression model
lr_model=LinearRegression()
lr_model.fit(x_train_scaled_l, y_train_l)

# Predicting popularity scores
y_predict_train_lr=lr_model.predict(x_train_scaled_l)
y_predict_test_lr=lr_model.predict(x_test_scaled_l)

# Calculating evaluation metrics
rmse_lr_train=root_mean_squared_error(y_train_l, y_predict_train_lr)
rmse_lr_test=root_mean_squared_error(y_test_l, y_predict_test_lr)
r2_lr_train=r2_score(y_train_l, y_predict_train_lr)
r2_lr_test=r2_score(y_test_l, y_predict_test_lr)

# Printing the final cleaned results
print(f"Linear Regression -> Train RMSE: {rmse_lr_train:.4f} | Test RMSE: {rmse_lr_test:.4f} | Train R2: {r2_lr_train:.4f} | Test R2: {r2_lr_test:.4f}")

"""Linear Regression coefficients"""

coef=lr_model.coef_
coef_df=pd.DataFrame(coef,index=x_linear.columns,columns=['Coefficients'])
coef_df.sort_values('Coefficients', ascending=False)

lr_data = {
    'Feature': ['release_year', 'acousticness', 'loudness', 'speechiness', 'duration_ms',
                'valence', 'tempo', 'danceability', 'liveness', 'instrumentalness', 'track_number'],
    'Coefficient': [12.201963, 1.239519, 0.823720, 0.715545, 0.051749,
                    -0.263855, -0.353392, -0.697242, -0.723767, -0.742150, -6.102098]
}

df_lr = pd.DataFrame(lr_data)
df_lr = df_lr.sort_values(by='Coefficient', ascending=False)

plt.figure(figsize=(7, 3.8))
sns.set_theme(style="whitegrid")

ax = sns.barplot(x='Feature', y='Coefficient', data=df_lr, color='#BB8FCE')

for container in ax.containers:
    ax.bar_label(container, fmt='%.2f', padding=3, fontsize=8)

plt.axhline(y=0, color='#5D6D7E', linestyle='--', linewidth=1.2)

plt.xlabel('Features', fontsize=9.5, labelpad=6)
plt.ylabel('Coefficient Value', fontsize=9.5, labelpad=6)
plt.xticks(rotation=45, ha='right', fontsize=8.5)
plt.yticks(fontsize=8.5)
plt.ylim(-8, 14)

sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.savefig('linear_regression_coefficients_beautiful.png', dpi=300, bbox_inches='tight')
plt.show()

""" Random Forest Model"""

# 2. Random Forest Model Tuning (With energy and without outliers)
x_forest = df_forest.drop(columns=['popularity', 'album_families'], axis=1)
y_forest = df_forest['popularity']

# Splitting df_forest into train-test by album families
gss_forest = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx_f, test_idx_f = next(gss_forest.split(x_forest, y_forest, groups=df_forest['album_families']))

# go to x_forest and y_forest and bring only the cells from indexes
x_train_f = x_forest.iloc[train_idx_f].copy()
y_train_f = y_forest.iloc[train_idx_f].copy()
x_test_f = x_forest.iloc[test_idx_f].copy()
y_test_f = y_forest.iloc[test_idx_f].copy()

# Feature Scaling (Normalization)
scaler_f = StandardScaler()
x_train_scaled_f = scaler_f.fit_transform(x_train_f)
x_test_scaled_f = scaler_f.transform(x_test_f)

# Creating lists to store metrics for each depth
rmse_train_forest = []
rmse_test_forest = []
r2_train_forest = []
r2_test_forest = []

# Running the loop for max_depth from 1 to 10
for i in range(1, 11):
    forest_model=RandomForestRegressor(n_estimators=100, max_depth=i, random_state=42)
    forest_model.fit(x_train_scaled_f, y_train_f)

    # Predicting popularity scores
    y_predict_train_forest = forest_model.predict(x_train_scaled_f)
    y_predict_test_forest = forest_model.predict(x_test_scaled_f)

    # Calculating evaluation metrics
    rmse_forest_train = root_mean_squared_error(y_train_f, y_predict_train_forest)
    rmse_forest_test = root_mean_squared_error(y_test_f, y_predict_test_forest)
    r2_forest_train = r2_score(y_train_f, y_predict_train_forest)
    r2_forest_test = r2_score(y_test_f, y_predict_test_forest)

    # Printing the final cleaned results for each depth
    print(f"RF Clean Depth {i} -> Train RMSE: {rmse_forest_train:.4f} | Test RMSE: {rmse_forest_test:.4f} | Train R2: {r2_forest_train:.4f} | Test R2: {r2_forest_test:.4f}")

    # Appending metrics to lists
    rmse_train_forest.append(rmse_forest_train)
    rmse_test_forest.append(rmse_forest_test)
    r2_train_forest.append(r2_forest_train)
    r2_test_forest.append(r2_forest_test)

"""Random Forest importance feafuers"""

feature_RF=forest_model.feature_importances_
feature_RF_df=pd.DataFrame(feature_RF,index=x_forest.columns,columns=['RF Features Importance'])
feature_RF_df.sort_values('RF Features Importance', ascending=False)

"""Gradient Boosting Model"""

#3. Gradient Boosting Model Tuning (With energy and without outliers)
from sklearn.ensemble import GradientBoostingRegressor

x_boost=df_forest.drop(columns=['popularity', 'album_families'], axis=1)
y_boost=df_forest['popularity']

# Splitting df_forest into train-test by album families for boosting
gss_boost=GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx_b, test_idx_b=next(gss_boost.split(x_boost, y_boost, groups=df_forest['album_families']))

# go to x_boost and y_boost and bring only the cells from indexes
x_train_b=x_boost.iloc[train_idx_b].copy()
y_train_b=y_boost.iloc[train_idx_b].copy()
x_test_b=x_boost.iloc[test_idx_b].copy()
y_test_b=y_boost.iloc[test_idx_b].copy()

# Feature Scaling (Normalization)
scaler_b=StandardScaler()
x_train_scaled_b=scaler_b.fit_transform(x_train_b)
x_test_scaled_b=scaler_b.transform(x_test_b)

# Creating lists to store metrics for each depth
rmse_train_boost=[]
rmse_test_boost=[]
r2_train_boost=[]
r2_test_boost=[]

# Running the loop for max_depth from 1 to 10
for i in range(1, 11):
    boost_model=GradientBoostingRegressor(n_estimators=100, max_depth=i, random_state=42)
    boost_model.fit(x_train_scaled_b, y_train_b)

    # Predicting popularity scores
    y_predict_train_boost=boost_model.predict(x_train_scaled_b)
    y_predict_test_boost=boost_model.predict(x_test_scaled_b)

    # Calculating evaluation metrics
    rmse_boost_train=root_mean_squared_error(y_train_b, y_predict_train_boost)
    rmse_boost_test=root_mean_squared_error(y_test_b, y_predict_test_boost)
    r2_boost_train=r2_score(y_train_b, y_predict_train_boost)
    r2_boost_test=r2_score(y_test_b, y_predict_test_boost)

    # Printing the final cleaned results for each depth
    print(f"GB Clean Depth {i} -> Train RMSE: {rmse_boost_train:.4f} | Test RMSE: {rmse_boost_test:.4f} | Train R2: {r2_boost_train:.4f} | Test R2: {r2_boost_test:.4f}")

    # Appending metrics to lists
    rmse_train_boost.append(rmse_boost_train)
    rmse_test_boost.append(rmse_boost_test)
    r2_train_boost.append(r2_boost_train)
    r2_test_boost.append(r2_boost_test)

"""Gradient Boosting Features Importance"""

feature_GB=boost_model.feature_importances_
feature_GB_df=pd.DataFrame(feature_GB, index=x_boost.columns, columns=['GB Features Imporantance'])
feature_GB_df.sort_values('GB Features Imporantance', ascending=False)

# Check unique test albums for Linear Regression
print("Linear Test Albums:", df_linear.iloc[test_idx_l]['album_families'].unique())

# Check unique test albums for Random Forest
print("Random Forest Test Albums:", df_forest.iloc[test_idx_f]['album_families'].unique())

# Check unique test albums for Gradient Boosting
print("Gradient Boosting Test Albums:", df_forest.iloc[test_idx_b]['album_families'].unique())

#Linear Test Albums: ['1989' 'evermore' 'folklore']
#Random Forest Test Albums: ['1989' 'evermore' 'folklore']
#Gradient Boosting Test Albums: ['1989' 'evermore' 'folklore']

"""Feature Importance Comparison barplot"""

importance_data = {
    'Feature': ['release_year', 'speechiness', 'track_number', 'valence', 'liveness',
                'tempo', 'energy', 'danceability', 'loudness', 'duration_ms',
                'acousticness', 'instrumentalness'],
    'Random Forest': [0.703566, 0.077969, 0.066741, 0.041192, 0.019487,
                      0.018982, 0.015298, 0.009617, 0.017776, 0.011985,
                      0.009036, 0.008354],
    'Gradient Boosting': [0.695670, 0.077818, 0.061640, 0.041391, 0.024454,
                         0.018863, 0.019809, 0.016152, 0.014881, 0.012667,
                         0.009596, 0.007057]
}

df_importance = pd.DataFrame(importance_data)
df_melted = df_importance.melt(id_vars='Feature', var_name='Model', value_name='Importance')

plt.figure(figsize=(7, 3.8))
sns.set_theme(style="whitegrid")

ax = sns.barplot(x='Feature', y='Importance', hue='Model', data=df_melted,
                 palette=['#BB8FCE', '#7FB3D5'])

for container in ax.containers:
    ax.bar_label(container, fmt='%.3f', padding=3, fontsize=7.5, rotation=90)

plt.xlabel('Features', fontsize=9.5, labelpad=6)
plt.ylabel('Importance Score (0.0 - 1.0)', fontsize=9.5, labelpad=6)
plt.xticks(rotation=45, ha='right', fontsize=8.5)
plt.yticks(fontsize=8.5)
plt.ylim(0, 0.85)

sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.savefig('feature_importance_comparison_beautiful.png', dpi=300, bbox_inches='tight')
plt.show()

"""Final Models Comparison Visualization

"""

# Depth 4 index from your loops
depth_4_idx = 3

# Model names for x-axis
models=['Linear Regression', 'Random Forest\n(Depth 4)', 'Gradient Boosting\n(Depth 4)']

# Collect RMSE values
train_rmse_vals=[rmse_lr_train, rmse_train_forest[depth_4_idx], rmse_train_boost[depth_4_idx]]
test_rmse_vals=[rmse_lr_test, rmse_test_forest[depth_4_idx], rmse_test_boost[depth_4_idx]]

x=np.arange(len(models))
width=0.35

# Compact size for presentations
plt.figure(figsize=(5.5, 4))
sns.set_theme(style="whitegrid")

# Plotting bars with Blue (Train) and Red (Test)
plt.bar(x - width/2, train_rmse_vals, width, label='Train RMSE', color='#3182CE', edgecolor='black', linewidth=0.5)
plt.bar(x + width/2, test_rmse_vals, width, label='Test RMSE', color='#EF4444', edgecolor='black', linewidth=0.5)

# Typography and labels adjusted for smaller layout
plt.title('RMSE Comparison', fontsize=11, fontweight='bold', pad=8)
plt.xticks(x, models, fontsize=8.5)
plt.ylabel('RMSE Value', fontsize=9.5)
plt.ylim(0, 18)
plt.legend(frameon=True, fontsize=8.5)

# Add value labels on top of the bars
for i in range(len(models)):
    plt.text(i - width/2, train_rmse_vals[i] + 0.4, f"{train_rmse_vals[i]:.2f}", ha='center', va='bottom', fontsize=8.5, fontweight='bold')
    plt.text(i + width/2, test_rmse_vals[i] + 0.4, f"{test_rmse_vals[i]:.2f}", ha='center', va='bottom', fontsize=8.5, fontweight='bold')

plt.tight_layout()
plt.savefig('rmse_comparison_small.png', dpi=300)
plt.show()

# Depth 4 index from your loops
depth_4_idx=3

# Model names for x-axis
models=['Linear Regression', 'Random Forest\n(Depth 4)', 'Gradient Boosting\n(Depth 4)']

# Collect R2 values
train_r2_vals=[r2_lr_train, r2_train_forest[depth_4_idx], r2_train_boost[depth_4_idx]]
test_r2_vals=[r2_lr_test, r2_test_forest[depth_4_idx], r2_test_boost[depth_4_idx]]

x=np.arange(len(models))
width=0.35

# Compact size for presentations
plt.figure(figsize=(5.5, 4))
sns.set_theme(style="whitegrid")

# Plotting bars with Blue (Train) and Red (Test)
plt.bar(x - width/2, train_r2_vals, width, label='Train R2', color='#3182CE', edgecolor='black', linewidth=0.5)
plt.bar(x + width/2, test_r2_vals, width, label='Test R2', color='#EF4444', edgecolor='black', linewidth=0.5)

# Zero baseline
plt.axhline(0, color='black', linewidth=1.2, linestyle='-')

# Typography and labels adjusted for smaller layout
plt.title('R2 Comparison', fontsize=11, fontweight='bold', pad=8)
plt.xticks(x, models, fontsize=8.5)
plt.ylabel('R2 Score', fontsize=9.5)
plt.ylim(-0.25, 1.05)  # Perfect fit for your 0.80 and 0.90 train values
plt.legend(frameon=True, fontsize=8.5)

# Add value labels dynamically
for i in range(len(models)):
    # Train text (positive)
    plt.text(i - width/2, train_r2_vals[i] + 0.02, f"{train_r2_vals[i]:.2f}", ha='center', va='bottom', fontsize=8.5, fontweight='bold')

    # Test text (negative values go below zero safely)
    if test_r2_vals[i] < 0:
        plt.text(i + width/2, test_r2_vals[i] - 0.03, f"{test_r2_vals[i]:.2f}", ha='center', va='top', fontsize=8.5, fontweight='bold')
    else:
        plt.text(i + width/2, test_r2_vals[i] + 0.02, f"{test_r2_vals[i]:.2f}", ha='center', va='bottom', fontsize=8.5, fontweight='bold')

plt.tight_layout()
plt.savefig('r2_comparison_small.png', dpi=300)
plt.show()

# =====================================================================
# PREMIUM & CLEAN VISUAL PROOF: PERFECT FOR PRESENTATION
# =====================================================================
import matplotlib.pyplot as plt
import seaborn as sns  # Fixed the import typo here
import pandas as pd
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

# 1. Generate predictions from your exact variables
df_test_final = df_forest.iloc[test_idx_f].copy()

rf_d4 = RandomForestRegressor(n_estimators=100, max_depth=4, random_state=42).fit(x_train_scaled_f, y_train_f)
gb_d4 = GradientBoostingRegressor(n_estimators=100, max_depth=4, random_state=42).fit(x_train_scaled_b, y_train_b)

df_test_final['RF_Predicted'] = rf_d4.predict(x_test_scaled_f)
df_test_final['GB_Predicted'] = gb_d4.predict(x_test_scaled_b)

# 2. Extract standard deviations ('std')
plot_summary = df_test_final.groupby(['album_families', 'release_year']).agg(
    Actual_Data=('popularity', 'std'),
    Random_Forest=('RF_Predicted', 'std'),
    Gradient_Boosting=('GB_Predicted', 'std')
).reset_index()

plot_summary['Album_Era'] = plot_summary['album_families'] + " (" + plot_summary['release_year'].astype(str) + ")"

# 3. Melt for Seaborn
df_melted_bars = plot_summary.melt(
    id_vars=['Album_Era'], value_vars=['Actual_Data', 'Random_Forest', 'Gradient_Boosting'],
    var_name='Model_Type', value_name='Standard_Deviation'
)
df_melted_bars['Model_Type'] = df_melted_bars['Model_Type'].map({
    'Actual_Data': 'Actual Song Variance',
    'Random_Forest': 'Random Forest (Depth 4)',
    'Gradient_Boosting': 'Gradient Boosting (Depth 4)'
})

plt.figure(figsize=(7.5, 4))
sns.set_theme(style="whitegrid")

premium_palette = ['#1E3A8A', '#E11D48', '#059669']

ax = sns.barplot(
    x='Album_Era', y='Standard_Deviation', hue='Model_Type',
    data=df_melted_bars, palette=premium_palette, edgecolor='black', linewidth=0.6,
    width=0.75
)

for container in ax.containers:
    ax.bar_label(container, fmt='%.2f', padding=4, fontsize=8, fontweight='semibold')

plt.xlabel('Album Family & Release Year (Test Set)', fontsize=9.5, labelpad=8)
plt.ylabel('Song Spread (Standard Deviation)', fontsize=9.5, labelpad=8)
plt.ylim(0, 14)

plt.legend(loc='upper center', bbox_to_anchor=(0.5, -0.18), ncol=3, frameon=True, fontsize=8.5)

plt.tight_layout()
plt.savefig('visual_variance_collapse_proof.png', dpi=300, bbox_inches='tight')
plt.show()